#' Internal function to get data types in a data table
#'
#' @param .data A longZight object generated by \code{\link{load_long_data}}
#' @examples
#' \dontrun{
#' getDataTypes(dataobject)
#' }

getDatatypes <- function(.data) {
  .data %>%
    dplyr::summarise_all(class) %>%
    dplyr::filter(dplyr::row_number() == dplyr::n())
}
