#' iNZight Helper Function to generate Lasagna plots
#'
#' Will, (if required) recode the data to Lasagna format using \code{\link{recode_long_lasagna}}
#' and provide a complete ready-to-output plot for iNZight or other purposes.
#'
#' @param .data A longZight object generated by \code{\link{load_long_data}}
#' @param response The response variable to be plotted as a Lasagna plot
#' @param xlab  Optional x-axis label
#' @param title Optional title
#' @param completecases Logical variable to exclude incomplete cases
#' @param sortorder (if \code{.data} is a \code{longZight} object) the sort order for \code{\link{recode_long_lasagna}}
#' @examples
#' \dontrun{
#' mydata %>%
#'   load_long_data(IDind, WAVE) %>%
#'   refactor_wave %>%
#'   iz_plot_lasagna(A5E, completecases = TRUE)
#' }
#' @export
iz_plot_lasagna <- function(...) {
  UseMethod("iz_plot_lasagna")
}

#' iNZight Helper Function to generate Lasagna plots from \code{longZightLasagna} objects
#' @rdname iz_plot_lasagna
#' @method iz_plot_lasagna longZightLasagna
#' @export
iz_plot_lasagna.longZightLasagna <- function(.data, response, xlab = "Wave", title = paste0("Plot of ", response), completecases = FALSE, ...) {
  print(.data %>%
          plot_long_lasagna +
          ggplot2::ggtitle(response))
}

#' iNZight Helper Function to generate Lasagna plots from \code{longZight} objects
#' @rdname iz_plot_lasagna
#' @method iz_plot_lasagna longZight
#' @export
iz_plot_lasagna.longZight <- function(.data, response, sortorder = 1, xlab = "Wave", title = paste0("Plot of ", response), completecases = FALSE, ...) {
  print(.data %>% recode_long_lasagna(response, sortorder, completecases, ts.args = FALSE) %>%
          plot_long_lasagna +
          ggplot2::ggtitle(response))
}
