#' Plotting function to generate Alluvial plots
#'
#' Generates a \code{\link[ggplot2:ggplot2-package]{ggplot2}} plot of the response variable encoded in the \code{longZightAlluv}
#' or \code{longZightLasagna} object,
#' plots are returned allowing further customisation using standard ggplot2 geometries.
#'
#' @param .data A \code{longZightAlluv} or \code{longZightLasagna} object generated by \code{\link{recode_long_alluvial}} or \code{\link{recode_long_lasagna}} respectively
#' @param fillfunc The fill function to use for colouring Alluvial flows, defaults to \code{ggplot2::\link[ggplot2:scale_colour_discrete]{scale_fill_discrete}()}, but \code{\link{alluvial_fill_discrete}} must be used if \code{highlight} is set.
#(only if \code{.data} inherits the \code{longZightAlluv} class)
#' @param highlight Response level to be highlighted
#(only if \code{.data} inherits the \code{longZightAlluv} class)
#' @param focus Time period to use as focus/origin point (only if \code{.data} inherits the \code{longZightAlluv} class)
#' @param alluvium Logical, if \code{.data} inherits the \code{longZightLasagna} class, whether to plot transitions (\code{FALSE}) or trace flows (\code{TRUE})
#' @examples
#' \dontrun{
#' mydata %>%
#'   load_long_data(IDind, WAVE) %>%
#'   refactor_wave %>%
#'   recode_long_alluvial(A5E) %>%
#'   plot_long_alluvial
#' }
#' @return \code{\link[ggplot2:ggplot2-package]{ggplot2}} plot with the data represented as an Alluvial diagram
#' @export
plot_long_alluvial <- function(.data, ...) {
  UseMethod("plot_long_alluvial")
}

#' Plotting function to generate Alluvial plots from \code{longZightAlluv} objects
#' @rdname plot_long_alluvial
#' @method plot_long_alluvial longZightAlluv
#' @export
plot_long_alluvial.longZightAlluv <- function(.data, fillfunc = ggplot2::scale_fill_discrete(), highlight = NULL, focus = NULL) {
  waves_vect <- attr(.data, 'wave_list')
  axes <- sapply(seq_len(length(waves_vect)), function(x) setNames(list(paste0("value_", waves_vect[x])), paste0("axis", x)))


  if (!is.null(focus) && focus %in% waves_vect) {
    fill_aes <- ggplot2::aes_string(fill = paste0("value_", focus))
    axes_idx <- which(focus == waves_vect)
  } else {
    fill_aes <- ggplot2::aes_string(fill = paste0("value_", waves_vect[1]))
    axes_idx <- 1
  }

  if (!is.null(highlight)) {
    focus_idx <- which(levels(forcats::fct_drop(dplyr::pull(.data, axes[[axes_idx]]))) == highlight)
    if (length(focus_idx) > 0)
      fillfunc <- alluvial_fill_discrete(focus = focus_idx[1])
  }

  .data %>% ggplot2::ggplot(do.call(ggplot2::aes_string, c(list(y = "Freq"), axes))) +
    ggalluvial::geom_flow(fill_aes) +
    ggplot2::labs(fill = "Value") +
    ggalluvial::geom_stratum(colour = "grey") +
    ggplot2::scale_x_discrete(limits = waves_vect) +
    fillfunc +
    ggplot2::geom_text(stat = "stratum", infer.label = TRUE)
}

#' Plotting function to generate Alluvial plots from \code{longZightLasagna} objects
#' @rdname plot_long_alluvial
#' @method plot_long_alluvial longZightLasagna
#' @export
plot_long_alluvial.longZightLasagna <- function(.data, alluvium = FALSE, fillfunc = ggplot2::scale_fill_discrete(), highlight = NULL, ...) {
  if (!is.null(highlight)) {
    focus_idx <- which(levels(dplyr::pull(.data, "place")) == highlight)
    if (length(focus_idx) > 0)
      fillfunc <- alluvial_fill_discrete(focus = focus_idx[1])
  }

  fill_aes <- ggplot2::aes_string(fill = "place")

  .data %>%
    ggplot2::ggplot(ggplot2::aes(x = wave, stratum = place, alluvium = alluvid, y = n, label = place, fill = place)) +
    {
      if (alluvium) ggalluvial::geom_alluvium(fill_aes) else ggalluvial::geom_flow(fill_aes)
    } +
    ggalluvial::geom_stratum(alpha = 1) +
    ggplot2::geom_text(stat = "stratum") +
    fillfunc
}


