#' Plotting function to generate Lasagna plots
#'
#' Generates a \code{\link[ggplot2:ggplot2-package]{ggplot2}} plot of the response variable encoded in the \code{longZightLasagna} object,
#' plots are returned allowing further customisation using standard ggplot2 geometries.
#'
#' @param .data A \code{longZightLasagna} object generated by \code{\link{recode_long_lasagna}}
#' @examples
#' \dontrun{
#' mydata %>%
#'   load_long_data(IDind, WAVE) %>%
#'   refactor_wave %>%
#'   recode_long_lasagna(A5E) %>%
#'   plot_long_lasagna
#' }
#' @return \code{\link[ggplot2:ggplot2-package]{ggplot2}} plot with the data represented as a Lasagna diagram
#' @export
plot_long_lasagna <- function(.data, ...) {
  UseMethod("plot_long_lasagna")
}

#' Plotting function to generate Lasagna plots from \code{longZightLasagna} objects
#' @rdname plot_long_lasagna
#' @method plot_long_lasagna longZightLasagna
#' @export
plot_long_lasagna.longZightLasagna <- function(.data, ...) {
  waves_vect <- attr(.data, 'wave_list')
  .data %>%
    ggplot2::ggplot(ggplot2::aes(x = as.integer(wave))) +
    ggplot2::geom_rect(ggplot2::aes(
      xmin = xmin, xmax = xmax,
      ymin = ymin, ymax = ymax, fill = place
    )) +
    ggplot2::scale_fill_brewer(palette = "Paired") +
    ggplot2::scale_x_continuous(breaks = seq_along(waves_vect), labels = waves_vect) +
    ggplot2::labs(x = "Time", y = "Count", fill = "Value")
}
