#' Plotting function for Spaghetti and Transitional plots
#'
#' @param .data A longZight object generated by \code{\link[longZight:load_long_data]{load_long_data}}
#' @param response The response variable to be plotted by an alluvial
#' @param subsetvar1 Name of variable to be used for colouring Spaghetti lines
#' @param subsetvar2 Name of variable to be used to bring forward \code{TRUE} values and grey out \code{FALSE} variables
#' @param subsetvar2rev Logical, reverse logic/processing of \code{subsetvar2}
#' @param facetvar Name of variable to be used for faceting
#' @param ts.args Logical control to switch pharsing method for variable options
#'
#' \code{subsetvar1}, \code{subsetvar2} and \code{facetvar} default to \code{NULL}
#'
#' @examples
#' \dontrun{
#' mydata %>%
#'   load_long_data(id, xp) %>%
#'   plot_long_line(ln_wages, ged, hispanic)
#' }
#' @export
plot_long_line <- function(.data, response, subsetvar1 = NULL, subsetvar2 = NULL, subsetvar2rev = FALSE, facetvar = NULL, ts.args = TRUE) {
  UseMethod("plot_long_line")
}

#' Plotting function for Spaghetti and Transitional plots for \code{longZight} objects
#' @rdname plot_long_line
#' @method plot_long_line longZight
#' @export
plot_long_line.longZight <- function(.data, response, subsetvar1 = NULL, subsetvar2 = NULL, subsetvar2rev = FALSE, facetvar = NULL, ts.args = TRUE) {
  id_param <- attr(.data, 'lZid')
  wave_param <- attr(.data, 'lZwave')
  if (ts.args)
    values_param <- rlang::ensym(response)
  else
    values_param <- rlang::sym(response)
  datatypes <- getDatatypes(.data)

  datavars <- c(id_param, wave_param, values_param)
  if (!all(datavars %in% colnames(.data))) {
    stop("Undefined variable")
  }

  if ((dplyr::pull(datatypes[wave_param]) == "numeric") && (dplyr::pull(datatypes[values_param]) == "numeric")) {
    plotdata <- .data %>%
      tsibble::as_tsibble(key = !!id_param,
                 index = !!wave_param,
                 regular = FALSE)
    plotdata %<>%
      dplyr::left_join( plotdata %>%
                   brolgar::features(!!values_param, brolgar::feat_monotonic))

    aes_gen <- ggplot2::aes_string(x = wave_param, y = values_param, group = id_param)
    #if (exists("subsetvar1") && subsetvar1 %in% colnames(plotdata))
    if (!is.null(subsetvar1) && any(subsetvar1 %in% colnames(plotdata))) {
      if (ts.args)
        subsetvar1 <- rlang::ensym(subsetvar1)
      else
        subsetvar1 <- rlang::sym(subsetvar1)
      aes_ss1 <- ggplot2::aes_string(x = wave_param, y = values_param, group = id_param, col = subsetvar1)
    } else
      aes_ss1 <- NULL

    tmp_data1 <- plotdata
    if (!is.null(subsetvar2) && any(subsetvar2 %in% colnames(plotdata))) {
      if (ts.args)
        subsetvar2 <- rlang::ensym(subsetvar2)
      else
        subsetvar2 <- rlang::sym(subsetvar2)

      tmp_data1 %<>% dplyr::filter(subsetvar2rev == (!!subsetvar2))
      tmp_data2 <- plotdata %>% dplyr::filter(!subsetvar2rev == (!!subsetvar2))
    } else {
      tmp_data2 <- NULL
    }

    p <- ggplot2::ggplot()
    if (!is.null(aes_ss1)) {
      if (!is.null(tmp_data2)) {
        p <- p + ggplot2::geom_line(aes_gen, tmp_data1, col = "grey") +
          ggplot2::geom_line(aes_ss1, tmp_data2)
      }
      else
        p <- p + ggplot2::geom_line(aes_ss1, tmp_data1)
    } else {
      if (!is.null(tmp_data2)) {
        p <- p + ggplot2::geom_line(aes_gen, tmp_data1, col = "grey") +
          ggplot2::geom_line(aes_gen, tmp_data2)
      }
      else
        p <- p + ggplot2::geom_line(aes_gen, tmp_data1)
    }
    p <- p + ggthemes::scale_color_colorblind()
    if (!is.null(facetvar) && any(facetvar %in% colnames(plotdata))) {
      if (ts.args)
        facetvar <- rlang::ensym(facetvar)
      else
        facetvar <- rlang::sym(facetvar)
      warning("facet")
      p <- p + ggplot2::facet_wrap(facetvar)
    }
    return(p)
    #return(print(p))
  } else {
    value_data <- dplyr::pull(.data, !!values_param)
    p <- .data %>%
      dplyr::left_join(.data %>%
                  dplyr::group_by(!!id_param) %>%
                    dplyr::summarise(firsttime = min(!!wave_param)) %>%
                    dplyr::ungroup() %>%
                    dplyr::arrange(firsttime) %>%
                    dplyr::select(-firsttime) %>%
                    dplyr::mutate(int.id = dplyr::row_number())) %>%
      dplyr::mutate(dodge = seq(-0.25, 0.25, length.out = max(int.id))[int.id], ypos = as.numeric(!!values_param) + dodge) %>%
      ggplot2::ggplot(aes_string(wave_param, "ypos", group = id_param)) +
      ggplot2::geom_step(alpha = 0.25, direction = 'hv') +
      ggplot2::scale_y_continuous(breaks = sort(unique(as.numeric(value_data))), labels = levels(value_data))
    return(p)
  }
}
