#' Function to convert \code{longZight} objects for an Alluvial plot
#'
#' @param .data A \code{longZight} object generated by \code{\link[longZight:load_long_data]{load_long_data}}
#' @param response The response variable to be plotted as an alluvial
#' @param completecases Logical variable to exclude incomplete cases
#' @param ts.args Logical, control to switch pharsing method for variable options
#' @examples
#' \dontrun{
#' mydata %>%
#'   load_long_data(IDind, WAVE) %>%
#'   refactor_wave %>%
#'   recode_long_alluvial(A5E)
#' }
#' @return A \code{longZightAlluv} object
#' @export

recode_long_alluvial <- function(.data, response, completecases, ts.args) {
  UseMethod("recode_long_alluvial")
}

#' @rdname recode_long_alluvial
#' @method recode_long_alluvial longZight
#' @export
recode_long_alluvial.longZight <- function(.data, response, completecases = FALSE, ts.args = TRUE) {
  id_param <- attr(.data, 'lZid')
  wave_param <- attr(.data, 'lZwave')
  if (ts.args)
    values_param <- rlang::ensym(response)
  else
    values_param <- rlang::sym(response)

  if (!(c(values_param) %in% colnames(.data))) {
    stop("Response column missing.")
  }

  subset_data <- .data %>% dplyr::select(!!id_param, !!wave_param, !!values_param) %>%
    dplyr::rename(id = !!id_param, wave = !!wave_param, value = !!values_param)



  subset_data %<>%
    dplyr::left_join(
      subset_data %>%
        dplyr::group_by(wave, value) %>%
        dplyr::summarise(n = dplyr::n()) %>%
        dplyr::mutate(sortorder = rank(1 / (c(n) + 1), ties.method = "last")) %>%
        dplyr::select(-n)
    ) %>%
    dplyr::arrange(wave) %>%
    tidyr::drop_na() %>%
    dplyr::mutate(wave = forcats::fct_drop(wave))

  waves_vect <- levels(dplyr::pull(subset_data, wave))
  chart_waves <- rlang::syms(paste0("value_", waves_vect))
  chart_sort <- rlang::syms(paste0("sortorder_", waves_vect))
  values_levels <- levels(dplyr::pull(subset_data, value))

  subset_data %<>%
    tidyr::pivot_wider(names_from = wave, values_from = c(value, sortorder)) %>%
    {
      if (completecases) tidyr::drop_na(.) else dplyr::mutate_if(., is.factor, forcats::fct_explicit_na)
    } %>%
    dplyr::group_by(!!!chart_waves) %>%
    dplyr::summarise(Freq = dplyr::n()) %>%
    dplyr::ungroup()


  class(subset_data) <- c("longZightAlluv", class(subset_data))
  attr(subset_data, 'wave_list') <- waves_vect
  return(subset_data)
}
