#' Helper function to convert a wave variable into an ordered factor
#'
#' @param .data A longZight object generated by \code{\link{load_long_data}}
#' @param subset  An optional vector of values to retain
#' @examples
#' \dontrun{
#' mydata %>%
#'   load_long_data(IDind, WAVE) %>%
#'   refactor_wave(c(2008, 2010, 2012))
#'   }
#' @return An \code{longZight} object with a modified wave variable.
#' @export
refactor_wave <- function(.data, subset = NULL) {
  UseMethod("refactor_wave")
}

#' Helper function to convert a wave variable into an ordered factor for longZight objects.
#' @rdname refactor_wave
#' @method refactor_wave longZight
#' @export
refactor_wave.longZight <- function(.data, subset = NULL) {
  wave_var <- attr(.data, "lZwave")

  if (!is.null(subset)) {
    .data %<>%
      dplyr::filter(!!wave_var %in% subset)
  }

  wave_data <- dplyr::pull(.data, wave_var)

  if (!(is.numeric(wave_data) || is.character(wave_data))) {
    warning("wave should be a numeric or character vector")
  }

  waves <- sort(unique(wave_data))
  .data[, wave_var] <- ordered(wave_data, levels = waves)
  return(.data)
}
